print("How old are you", end = ' ')
age = input()
print("How tall are you", end = ' ')
height = input()
print("How much do yu weigh")
weight = input()
print(f"So you are {age} years old, {height} cm tall and {weight} kilos")